In [9]:
import numpy as np

### numpy array

In [10]:
benimListem= [20,30,40]

In [11]:
type(benimListem)

list

In [14]:
np.array(benimListem)

array([20, 30, 40])

In [15]:
matrixListesi=[(10,20,30),(40,50,60),(70,80,90)]

In [16]:
np.array(matrixListesi)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

### arange


In [17]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### zeros

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### linspace

In [21]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

### eye

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### random

In [26]:
np.random.randn(4,2)

array([[ 0.37810507, -0.0780545 ],
       [ 0.45110907,  0.37215483],
       [-1.37843292, -0.24682269],
       [-1.59091691,  2.06274763]])

In [27]:
np.random.randint(1,10)

3

In [28]:
np.random.randint(1,300,5)

array([107, 160, 136, 104,  96])

In [49]:
benimRandomDizim= np.random.randint(0,50,20)

In [50]:
benimRandomDizim

array([23, 44, 25,  2, 33, 36, 28, 37, 47, 28,  7, 41, 23, 29, 39, 15, 19,
       29, 49,  7])

### numpy dizi methodları

In [59]:
benimRandomDizim= np.random.randint(0,100,20)

In [60]:
benimRandomDizim.reshape(4,5)

array([[34, 73, 71, 79, 61],
       [96, 77, 98,  8, 52],
       [16, 72, 84, 98, 46],
       [22, 55, 56, 87, 57]])

In [61]:
benimRandomDizim.max()

98

In [62]:
benimRandomDizim.min()

8

In [63]:
benimRandomDizim.argmax()

7

In [64]:
benimRandomDizim.argmin()

8

In [65]:
benimRandomDizim.shape

(20,)

In [66]:
reshapeDizim=benimRandomDizim.reshape(4,5)

In [68]:
reshapeDizim.shape

(4, 5)