In [3]:
import numpy as np

In [5]:
benimDizim=np.arange(0,15)

In [6]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
benimDizim[5]

5

In [9]:
benimDizim[3:7]

array([3, 4, 5, 6])

In [10]:
benimDizim[3:8]=-5

In [11]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [13]:
baskaDizi=np.arange(0,24)

In [14]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [18]:
slicingDizisi=baskaDizi[4:9]

In [19]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [20]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [21]:
slicingDizisi[:]=700

In [22]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [23]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [24]:
ornekDizi=np.arange(0,24)

In [28]:
ornekDiziKopyası=C.copy()

In [29]:
ornekDiziKopyası

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [31]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [32]:
ornekDiziKopyasıSlicing=ornekDiziKopyası[3:6]

In [33]:
ornekDiziKopyasıSlicing[:]=800

In [34]:
ornekDiziKopyasıSlicing

array([800, 800, 800])

In [35]:
ornekDiziKopyası

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [36]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

### matrix

In [38]:
benimListem=[[10,20,30],[20,30,40],[40,50,60]]

In [40]:
ornekMatrixDizisi=np.array(benimListem)

In [41]:
ornekMatrixDizisi

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [42]:
ornekMatrixDizisi[0]

array([10, 20, 30])

In [44]:
ornekMatrixDizisi[1][2]

40

In [45]:
ornekMatrixDizisi[1,2]

40

In [46]:
ornekMatrixDizisi[1:,2]

array([40, 60])

In [47]:
ornekMatrixDizisi[0:,2]

array([30, 40, 60])

In [48]:
ornekMatrixDizisi[2:,2:]

array([[60]])

In [49]:
yeniListe=[[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [50]:
yeniMatrix=  np.array(yeniListe)

In [51]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
yeniMatrix[[0,2,4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [53]:
yeniMatrix[[4,2,0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

### operasyonlar

In [57]:
yeniBirDizi=np.random.randint(1,100,20)

In [60]:
yeniBirDizi

array([43, 72, 59, 47, 14, 57, 29, 29, 27, 50, 77, 54, 18, 83, 26, 22, 88,
       80,  5, 55])

In [61]:
yeniBirDizi>24

array([ True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True,  True,
       False,  True])

In [62]:
sonucDizisi=yeniBirDizi>24

In [63]:
sonucDizisi

array([ True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True,  True,
       False,  True])

In [64]:
yeniBirDizi

array([43, 72, 59, 47, 14, 57, 29, 29, 27, 50, 77, 54, 18, 83, 26, 22, 88,
       80,  5, 55])

In [65]:
yeniBirDizi[sonucDizisi]

array([43, 72, 59, 47, 57, 29, 29, 27, 50, 77, 54, 83, 26, 88, 80, 55])

In [66]:
sonDizi=np.arange(0,24)

In [67]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [68]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [69]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [70]:
sonDizi*sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [71]:
sonDizi-sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [72]:
sonDizi/sonDizi

C:\Users\dilay\AppData\Local\Temp\ipykernel_6880\1954055075.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi/sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [73]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [74]:
np.max(sonDizi)

23